### ISSUE TITLE
Has anyone figured out how to get the bots running?

### ISSUE THREAD

**Issue by EternityX** [ohMatty/CSGOShop#5]
I got the site functional but I'm not quite sure how the bots interact with the site. 
I went through some of the bot's code and it seems some of the webside files are not provided?

For example:

``` c#
string PostGetMessages()
        {
            Bot.log.Info("Submitting /api/messages/...");
            var postUrl = "http://staging.csgoshop.com/api/messages/";
            var data = new System.Collections.Specialized.NameValueCollection();
            data.Add("key", Bot.CSGOShopAPIKey);
            postUrl += "?sig=" + Bot.CreateSHA256(Bot.CSGOShopAPIKey, Bot.CSGOShopAPIKey);           
            return SteamWeb.Fetch(postUrl, "POST", data, null, false, "http://staging.csgoshop.com");
        }
```

If I've missed something, please tell me.

**Comment by carlesnunez** [comment]
do you know how the routes work?

Do you know that you need to put the running routes into that line in csgoshop.class?
$redirect_endpoints = ['admin', 'preregister', 'banned', 'account/terms','account/inventory', 'account/settings', 'account/login', 'account/logout', 'account/listings', 'account/wallet', 'account/orders/active', 'account/orders', 'data/inventory', 'request', 'browse', 'support', 'help', 'affiliates', 'staff', 'bots', 'featured', 'notifications'];

**Comment by EternityX** [comment]
I did not know that. 
Thank you very much :)

**Comment by jamie-0-1** [comment]
You don't have to put the routes in the redirect endpoints... the only things that go in there are routes that avoid the redirect for not logged in etc

**Comment by ElPresidentePro** [comment]
eternityX add me steam pls http://steamcommunity.com/id/73214214549367/
